language: node_js
node_js:
  - 12
install:
  - yarn install
build:
  - yarn build
deploy:
  provider: surge
  project: ./build/
  domain: https://pr-${TRAVIS_PULL_REQUEST}.maxvektor-money-counter.surge.sh/
  on:
    all_branches: true
